window.JERI_ROTA_SERVICES = {
  "onibus-madrugada": {
    eyebrow: "Transporte para Jericoacoara",
    title: "Ônibus da Madrugada",
    lead: "Organize seu deslocamento para Jericoacoara com atendimento direto e orientação da equipe local.",
    hero: "/Onibus.jpg",
    summary: [["Modalidade", "Sob consulta"], ["Horário", "Confirmado no atendimento"], ["Reserva", "Pelo WhatsApp"]],
    description: "A Jeri Rota ajuda a organizar os detalhes do transporte, confirmar as condições disponíveis para a sua data e orientar você antes do embarque.",
    route: ["Envie a data, origem, destino e quantidade de passageiros.", "A equipe verifica as opções disponíveis para o seu pedido.", "Você recebe as condições e orientações pelo WhatsApp.", "Após a confirmação, os detalhes do embarque são enviados por escrito."],
    included: ["Atendimento direto pelo WhatsApp", "Orientações para o embarque", "Confirmação dos detalhes da reserva"],
    notIncluded: ["Itens não descritos na proposta", "Serviços extras não combinados previamente"],
    gallery: [["/Onibus.jpg", "Ônibus para transporte de passageiros"], ["/assets/pilar-transporte.jpg", "Transporte organizado pela Jeri Rota"], ["/img/transfer-jeri.jpg", "Chegada e saída de Jericoacoara"]],
    important: ["Horários, pontos de embarque e disponibilidade são confirmados no atendimento.", "Informe corretamente a data e a quantidade de passageiros.", "Consulte as condições da proposta antes de confirmar."],
    message: "Olá! Quero informações sobre o Ônibus da Madrugada para Jericoacoara."
  },
  "hospedagem-jericoacoara": {
    eyebrow: "Onde ficar em Jericoacoara",
    title: "Hospedagem em Jericoacoara",
    lead: "Pousadas e hotéis selecionados de acordo com seu estilo de viagem, conforto e localização.",
    hero: "/Hospedagem.jpg",
    summary: [["Curadoria", "Personalizada"], ["Localização", "Conforme sua preferência"], ["Disponibilidade", "Sob consulta"]],
    description: "A Jeri Rota ajuda você a encontrar uma hospedagem alinhada ao seu planejamento. Conte o perfil da viagem e receba opções disponíveis para avaliar com tranquilidade.",
    route: ["Informe as datas, número de hóspedes e preferências.", "A equipe pesquisa opções adequadas ao perfil da viagem.", "Você recebe alternativas e condições pelo WhatsApp.", "Após sua escolha, a reserva segue conforme a proposta apresentada."],
    included: ["Curadoria de opções", "Atendimento pelo WhatsApp", "Orientação sobre localização e perfil da hospedagem"],
    notIncluded: ["Serviços não descritos na proposta da hospedagem", "Consumos e extras contratados diretamente no local"],
    gallery: [["/Hospedagem.jpg", "Hospedagem com piscina em Jericoacoara"], ["/img/hospedagem.jpg", "Opção de hospedagem selecionada"], ["/assets/pilar-hospedagem.jpg", "Conforto durante a estadia"]],
    important: ["Valores e disponibilidade dependem das datas e da quantidade de hóspedes.", "Políticas de entrada, saída e cancelamento são informadas na proposta.", "Confira o que está incluído antes de confirmar a reserva."],
    message: "Olá! Quero opções de hospedagem em Jericoacoara."
  },
  "passeio-lado-oeste": {
    eyebrow: "Experiências em Jericoacoara",
    title: "Passeio Lado Oeste",
    lead: "Descubra paisagens do litoral oeste com organização local e os detalhes combinados antes da saída.",
    hero: "/Oeste.jpg",
    summary: [["Roteiro", "Confirmado no atendimento"], ["Modalidade", "Sob consulta"], ["Saída", "Combinada previamente"]],
    description: "O passeio pelo lado oeste é organizado conforme a data, o perfil do grupo e as condições disponíveis. A equipe explica o roteiro e as orientações importantes antes da reserva.",
    route: ["Envie a data e a quantidade de participantes.", "A equipe apresenta o roteiro e as modalidades disponíveis.", "Você recebe as condições e confirma sua escolha.", "Ponto de encontro e orientações são enviados pelo WhatsApp."],
    included: ["Organização do passeio contratado", "Informações do roteiro antes da confirmação", "Suporte da equipe pelo WhatsApp"],
    notIncluded: ["Entradas, consumos ou taxas não descritas na proposta", "Atividades opcionais contratadas durante o passeio"],
    gallery: [["/Oeste.jpg", "Experiência no passeio do lado oeste"], ["/img/oeste.jpg", "Paisagem do litoral oeste"], ["/img/quadri.jpg", "Aventura nas paisagens de Jericoacoara"]],
    important: ["Roteiro, duração e modalidade são confirmados na proposta.", "Atividades opcionais e eventuais taxas devem ser consultadas.", "As condições do passeio podem ser ajustadas por segurança ou fatores naturais."],
    message: "Olá! Quero cotar o Passeio Lado Oeste em Jericoacoara."
  },
  "extremo-leste": {
    eyebrow: "Roteiro especial",
    title: "Passeio Extremo Leste",
    lead: "Uma experiência para explorar mais do litoral, com roteiro e condições apresentados antes da confirmação.",
    hero: "/Extremo.jpg",
    summary: [["Roteiro", "Sob consulta"], ["Disponibilidade", "Conforme a data"], ["Atendimento", "Direto pelo WhatsApp"]],
    description: "Conte à equipe quando pretende viajar e quantas pessoas participarão. A Jeri Rota verifica as opções para o Extremo Leste e orienta você sobre os detalhes disponíveis.",
    route: ["Informe a data e o perfil do seu grupo.", "Receba as opções de roteiro disponíveis.", "Confira inclusões, condições e orientações.", "Confirme e receba os detalhes de saída pelo WhatsApp."],
    included: ["Organização do serviço confirmado", "Orientações antes da saída", "Atendimento local pelo WhatsApp"],
    notIncluded: ["Itens não descritos na proposta", "Entradas, consumos e atividades opcionais não confirmados"],
    gallery: [["/Extremo.jpg", "Dunas no roteiro Extremo Leste"], ["/img/passeio.jpg", "Passeio pelas paisagens de Jericoacoara"], ["/assets/pilar-passeios.jpg", "Experiência de passeio com a Jeri Rota"]],
    important: ["Consulte o roteiro e as paradas válidas para sua data.", "Duração, modalidade e valores são informados no atendimento.", "Condições naturais podem exigir ajustes no roteiro."],
    message: "Olá! Quero informações sobre o Passeio Extremo Leste."
  },
  "transfer-4x4": {
    eyebrow: "Chegue a Jeri com organização",
    title: "Transfer Hilux 4x4",
    lead: "Transfer compartilhado ou privativo com atendimento direto e detalhes combinados antes da viagem.",
    hero: "/Hillux.jpg",
    summary: [["Modalidade", "Compartilhada ou privativa"], ["Rota", "Sob consulta"], ["Confirmação", "Pelo WhatsApp"]],
    description: "Informe origem, destino, data e número de passageiros. A equipe verifica a opção adequada e envia a proposta com as orientações para o deslocamento.",
    route: ["Envie origem, destino, data e quantidade de passageiros.", "A equipe verifica rota, modalidade e disponibilidade.", "Você recebe a proposta e confirma os dados.", "As orientações de embarque são enviadas pelo WhatsApp."],
    included: ["Transfer conforme a rota confirmada", "Orientações de embarque", "Atendimento pelo WhatsApp"],
    notIncluded: ["Paradas ou desvios não combinados", "Serviços extras não descritos na proposta"],
    gallery: [["/Hillux.jpg", "Hilux 4x4 para transfer"], ["/img/transfer-hero-duna-mar.jpg", "Transfer pelas paisagens da região"], ["/img/transfer-jeri.jpg", "Transfer para Jericoacoara"]],
    important: ["Origem, destino, horários e pontos de encontro devem ser confirmados.", "Informe a quantidade de passageiros e bagagens no atendimento.", "Consulte as condições da modalidade compartilhada ou privativa."],
    message: "Olá! Quero cotar um Transfer Hilux 4x4."
  },
  "rota-das-emocoes": {
    eyebrow: "Roteiro personalizado",
    title: "Rota das Emoções",
    lead: "Planeje uma experiência pela Rota das Emoções com atendimento local e roteiro construído conforme sua viagem.",
    hero: "/Rotaemoção.jpg",
    summary: [["Roteiro", "Personalizado"], ["Datas", "Sob consulta"], ["Planejamento", "Pelo WhatsApp"]],
    description: "A Jeri Rota ajuda a organizar as possibilidades do roteiro conforme as datas, o grupo e as preferências informadas. A proposta é apresentada antes de qualquer confirmação.",
    route: ["Conte suas datas, quantidade de viajantes e preferências.", "A equipe avalia possibilidades de roteiro personalizado.", "Você recebe uma proposta com os serviços considerados.", "Após a confirmação, as orientações são organizadas pelo WhatsApp."],
    included: ["Planejamento conforme a proposta aprovada", "Atendimento pelo WhatsApp", "Orientações dos serviços confirmados"],
    notIncluded: ["Serviços, taxas e consumos não descritos na proposta", "Alterações de roteiro não confirmadas previamente"],
    gallery: [["/Rotaemoção.jpg", "Paisagem da Rota das Emoções"], ["/img/rota-das-emocoes.png", "Experiências da Rota das Emoções"], ["/assets/pilar-passeios.jpg", "Roteiros organizados pela Jeri Rota"]],
    important: ["O roteiro final depende das datas, disponibilidade e preferências do grupo.", "Valores, duração e serviços incluídos são informados na proposta.", "Leia as condições de cada serviço antes da confirmação."],
    message: "Olá! Quero montar um roteiro pela Rota das Emoções."
  },
  "passeio-lado-leste": {
    eyebrow: "Experiências em Jericoacoara",
    title: "Passeio Lado Leste",
    lead: "Conheça paisagens do litoral leste com apoio local e informações claras antes da saída.",
    hero: "/Leste.jpg",
    summary: [["Roteiro", "Confirmado no atendimento"], ["Modalidade", "Sob consulta"], ["Reserva", "Pelo WhatsApp"]],
    description: "A equipe ajuda a escolher a opção disponível para a data e o perfil do grupo, apresentando roteiro, modalidade e condições antes da confirmação.",
    route: ["Envie a data e a quantidade de participantes.", "A equipe apresenta o roteiro e as opções disponíveis.", "Confira as condições e confirme sua escolha.", "Receba o ponto de encontro e as orientações pelo WhatsApp."],
    included: ["Organização do passeio contratado", "Informações do roteiro antes da confirmação", "Atendimento local pelo WhatsApp"],
    notIncluded: ["Entradas, consumos ou taxas não descritas na proposta", "Atividades opcionais contratadas durante o passeio"],
    gallery: [["/Leste.jpg", "Paisagem do passeio lado leste"], ["/img/rede2.jpg", "Parada para aproveitar Jericoacoara"], ["/img/passeio.jpg", "Passeio pelas paisagens da região"]],
    important: ["Roteiro, duração e modalidade são confirmados na proposta.", "Consulte entradas, atividades opcionais e eventuais taxas.", "Condições naturais podem exigir ajustes no roteiro."],
    message: "Olá! Quero cotar o Passeio Lado Leste em Jericoacoara."
  }
};
