window.JERI_ROTA_SERVICES = {
  "onibus-madrugada": {
    eyebrow: "Transporte para Jericoacoara",
    title: "Ônibus da Madrugada",
    lead: "Organize seu deslocamento para Jericoacoara com atendimento direto e orientação da equipe local.",
    hero: "/Onibus.jpg",
    summary: [["Valor inicial", "R$ 200 por pessoa"], ["Modalidade", "Compartilhada"], ["Trecho e horário", "Confirmados na proposta"]],
    description: "A Jeri Rota ajuda a organizar os detalhes do transporte, confirmar as condições disponíveis para a sua data e orientar você antes do embarque.",
    route: ["Envie a data, origem, destino e quantidade de passageiros.", "A equipe verifica o trecho, o horário e o ponto de embarque disponíveis para a sua data.", "Você recebe valor, condições, bagagens permitidas e orientações pelo WhatsApp.", "Após a confirmação manual da reserva, os detalhes do embarque são enviados por escrito."],
    included: ["Transporte no trecho confirmado na proposta", "Atendimento direto pelo WhatsApp", "Orientações de horário e ponto de embarque", "Confirmação dos detalhes da reserva"],
    notIncluded: ["Trechos adicionais não descritos na proposta", "Serviços extras não combinados previamente", "Despesas pessoais durante o trajeto"],
    gallery: [["/Onibus.jpg", "Ônibus para transporte de passageiros"], ["/assets/pilar-transporte.jpg", "Transporte organizado pela Jeri Rota"], ["/img/transfer-jeri.jpg", "Chegada e saída de Jericoacoara"]],
    important: ["O valor de R$ 200 é uma referência inicial por pessoa e pode variar conforme data, trecho e disponibilidade.", "Horário, duração estimada, ponto de embarque e desembarque são confirmados antes do pagamento.", "Informe corretamente a quantidade de passageiros e bagagens.", "A solicitação enviada pelo site ou WhatsApp só se torna reserva após confirmação da equipe."],
    message: "Olá! Quero informações sobre o Ônibus da Madrugada para Jericoacoara."
  },
  "hospedagem-jericoacoara": {
    eyebrow: "Onde ficar em Jericoacoara",
    title: "Hospedagem em Jericoacoara",
    lead: "Pousadas e hotéis selecionados de acordo com seu estilo de viagem, conforto e localização.",
    hero: "/Hospedagem.jpg",
    summary: [["Valor inicial", "R$ 350 por diária"], ["Acomodação", "Conforme disponibilidade"], ["Período", "Confirmado na proposta"]],
    description: "A Jeri Rota ajuda você a encontrar uma hospedagem alinhada ao seu planejamento. Conte o perfil da viagem e receba opções disponíveis para avaliar com tranquilidade.",
    route: ["Informe as datas, número de hóspedes e preferências.", "A equipe pesquisa opções adequadas ao perfil da viagem.", "Você recebe alternativas com valor da diária, tipo de acomodação, localização, café da manhã quando aplicável e condições pelo WhatsApp.", "Após sua escolha, a reserva segue conforme a proposta apresentada e a confirmação da equipe."],
    included: ["Curadoria de opções", "Atendimento pelo WhatsApp", "Orientação sobre localização e perfil da hospedagem", "Informações sobre o que está incluído em cada diária apresentada"],
    notIncluded: ["Serviços não descritos na proposta da hospedagem", "Consumos, frigobar, taxas locais e extras contratados diretamente no local quando não incluídos"],
    gallery: [["/Hospedagem.jpg", "Hospedagem com piscina em Jericoacoara"], ["/img/hospedagem.jpg", "Opção de hospedagem selecionada"], ["/assets/pilar-hospedagem.jpg", "Conforto durante a estadia"]],
    important: ["O valor de R$ 350 é uma referência inicial por diária e depende das datas, quantidade de hóspedes e categoria da acomodação.", "Check-in, check-out, alimentação incluída, política de crianças e cancelamento são informados na proposta.", "Confira o que está incluído antes de confirmar a reserva."],
    message: "Olá! Quero opções de hospedagem em Jericoacoara."
  },
  "passeio-lado-oeste": {
    eyebrow: "Experiências em Jericoacoara",
    title: "Passeio Lado Oeste",
    lead: "Descubra paisagens do litoral oeste com organização local e os detalhes combinados antes da saída.",
    hero: "/Oeste.jpg",
    summary: [["Valor inicial", "R$ 110 por pessoa"], ["Modalidade", "Compartilhada; privativo sob consulta"], ["Duração média", "Cerca de 6 horas"]],
    description: "Uma experiência completa pelo lado oeste, com natureza preservada, travessias, dunas e lagoas. O percurso é realizado pela praia em veículo 4x4, com condutor experiente.",
    itinerary: [["Faixa de areia de Jericoacoara", "A saída acontece pela praia, com paisagens litorâneas que abrem o caminho para o lado oeste."], ["Manguezal e Cavalo-Marinho", "Há a possibilidade de incluir o passeio ecológico de barco pelo manguezal para observar cavalos-marinhos."], ["Travessia para Camocim", "A rota segue pela balsa na divisa entre Jericoacoara e Camocim, uma passagem marcante da experiência."], ["Manguezais e dunas", "Paradas para fotos valorizam a biodiversidade do manguezal antes de percorrer aproximadamente 8 km de dunas."], ["Aventura nas lagoas", "Atividades opcionais nas dunas, como skibunda, toboágua e tirolesa, podem complementar o passeio."], ["Pausa para almoço", "O roteiro reserva uma parada para almoço e para aproveitar o ritmo tranquilo da região."]],
    route: ["Envie a data, quantidade de participantes e local de hospedagem ou embarque.", "A equipe apresenta o roteiro previsto, duração aproximada, modalidade e transporte disponíveis.", "Você recebe valor, inclusões, eventuais taxas ou atividades opcionais e confirma sua escolha.", "Ponto e horário de encontro são enviados pelo WhatsApp após a confirmação manual da reserva."],
    included: ["Transporte conforme a modalidade confirmada", "Organização do passeio contratado", "Informações do roteiro, duração e embarque antes da confirmação", "Suporte da equipe pelo WhatsApp"],
    notIncluded: ["Entradas, consumos ou taxas não descritas na proposta", "Alimentação quando não indicada como incluída", "Atividades opcionais contratadas durante o passeio"],
    gallery: [["/oeste-lagoa-aerea.jpeg", "Vista aérea da lagoa e da estrutura do passeio no lado oeste"], ["/oeste-barcos.jpeg", "Visitantes junto aos barcos no litoral oeste"], ["/oeste-duna-lagoa.jpeg", "Descida de duna até a lagoa no passeio lado oeste"]],
    important: ["O valor de R$ 110 é uma referência inicial por pessoa na modalidade compartilhada; opção privativa é cotada conforme grupo e data.", "Roteiro, paradas, duração aproximada, transporte, horário e local de embarque são confirmados na proposta.", "Atividades opcionais, entradas, alimentação e eventuais taxas são informadas separadamente quando não incluídas.", "Condições naturais ou de segurança podem exigir ajustes no roteiro."],
    message: "Olá! Quero cotar o Passeio Lado Oeste em Jericoacoara."
  },
  "extremo-leste": {
    eyebrow: "Roteiro especial",
    title: "Passeio Extremo Leste",
    lead: "Uma experiência para explorar mais do litoral, com roteiro e condições apresentados antes da confirmação.",
    hero: "/Extremo.jpg",
    summary: [["Valor inicial", "R$ 150 por pessoa"], ["Modalidade", "Compartilhada; privativo sob consulta"], ["Duração e saída", "Confirmadas na proposta"]],
    description: "Conte à equipe quando pretende viajar e quantas pessoas participarão. A Jeri Rota verifica as opções para o Extremo Leste e apresenta roteiro, duração aproximada, transporte, embarque e condições antes da confirmação.",
    route: ["Informe a data, quantidade de pessoas e local de embarque ou hospedagem.", "Receba o roteiro previsto, duração aproximada, modalidade e transporte disponíveis.", "Confira valor, inclusões, despesas extras e orientações importantes.", "Confirme a solicitação e receba ponto e horário de saída pelo WhatsApp."],
    included: ["Transporte conforme modalidade confirmada", "Organização do serviço confirmado", "Roteiro e duração informados antes da saída", "Atendimento local pelo WhatsApp"],
    notIncluded: ["Itens não descritos na proposta", "Entradas, consumos, alimentação e atividades opcionais não confirmados"],
    gallery: [["/Extremo.jpg", "Dunas no roteiro Extremo Leste"], ["/img/passeio.jpg", "Passeio pelas paisagens de Jericoacoara"], ["/assets/pilar-passeios.jpg", "Experiência de passeio com a Jeri Rota"]],
    important: ["O valor de R$ 150 é uma referência inicial por pessoa na modalidade compartilhada; opção privativa é cotada separadamente.", "Roteiro, paradas, duração aproximada, transporte e embarque são informados antes do pagamento.", "Entradas, alimentação, atividades opcionais e demais despesas extras são discriminadas quando aplicáveis.", "Condições naturais podem exigir ajustes no roteiro."],
    message: "Olá! Quero informações sobre o Passeio Extremo Leste."
  },
  "transfer-4x4": {
    eyebrow: "Chegue a Jeri com organização",
    title: "Transfer Hilux 4x4",
    lead: "Transfer compartilhado ou privativo com atendimento direto e detalhes combinados antes da viagem.",
    hero: "/Hillux.jpg",
    summary: [["Valor inicial", "R$ 800 por veículo/trecho"], ["Modalidade", "Privativa; compartilhada sob consulta"], ["Rota e horário", "Confirmados na proposta"]],
    description: "Informe origem, destino, data e número de passageiros. A equipe verifica a opção adequada e envia a proposta com valor, modalidade, rota, duração estimada e orientações para o deslocamento.",
    route: ["Envie origem, destino, data, quantidade de passageiros, bagagens e horário desejado.", "A equipe verifica rota, duração estimada, modalidade, capacidade e disponibilidade.", "Você recebe a proposta com valor do trecho e confirma os dados.", "Após a confirmação manual da reserva, horário e local de embarque são enviados pelo WhatsApp."],
    included: ["Veículo e motorista para o trecho confirmado", "Transfer conforme a rota e modalidade descritas na proposta", "Orientações de embarque", "Atendimento pelo WhatsApp"],
    notIncluded: ["Paradas, desvios ou trechos adicionais não combinados", "Serviços extras não descritos na proposta", "Despesas pessoais durante o trajeto"],
    gallery: [["/Hillux.jpg", "Hilux 4x4 para transfer"], ["/img/transfer-hero-duna-mar.jpg", "Transfer pelas paisagens da região"], ["/img/transfer-jeri.jpg", "Transfer para Jericoacoara"]],
    important: ["O valor de R$ 800 é uma referência inicial por veículo e por trecho; rota, capacidade, data e modalidade podem alterar o valor final.", "Origem, destino, duração estimada, horários, pontos de encontro e bagagens devem ser confirmados antes do pagamento.", "A solicitação enviada pelo site não confirma automaticamente a reserva; a equipe confirma disponibilidade e condições pelo WhatsApp."],
    message: "Olá! Quero cotar um Transfer Hilux 4x4."
  },
  "rota-das-emocoes": {
    eyebrow: "Roteiro personalizado",
    title: "Rota das Emoções",
    lead: "Planeje uma experiência pela Rota das Emoções com atendimento local e roteiro construído conforme sua viagem.",
    hero: "/Rotaemoção.jpg",
    summary: [["Valor inicial", "R$ 5.000 por pacote/roteiro"], ["Roteiro", "Personalizado"], ["Duração e serviços", "Definidos na proposta"]],
    description: "A Jeri Rota ajuda a organizar as possibilidades do roteiro conforme as datas, o grupo e as preferências informadas. Transporte, hospedagens, duração, inclusões e demais serviços são discriminados na proposta antes de qualquer confirmação.",
    route: ["Conte suas datas, quantidade de viajantes, origem, destino final e preferências.", "A equipe avalia possibilidades de roteiro, duração e logística entre os destinos.", "Você recebe uma proposta com transporte, hospedagens e demais serviços considerados, além das despesas não incluídas.", "Após a confirmação, embarques, horários e orientações são organizados pelo WhatsApp."],
    included: ["Planejamento conforme a proposta aprovada", "Serviços discriminados individualmente na proposta", "Atendimento pelo WhatsApp", "Orientações dos serviços confirmados"],
    notIncluded: ["Serviços, taxas, alimentação, entradas e consumos não descritos na proposta", "Alterações de roteiro não confirmadas previamente"],
    gallery: [["/Rotaemoção.jpg", "Paisagem da Rota das Emoções"], ["/img/rota-das-emocoes.png", "Experiências da Rota das Emoções"], ["/assets/pilar-passeios.jpg", "Roteiros organizados pela Jeri Rota"]],
    important: ["O valor de R$ 5.000 é uma referência inicial para um pacote/roteiro e varia conforme número de viajantes, duração, transportes, hospedagens e serviços escolhidos.", "O roteiro final, a duração, os locais de embarque e os serviços incluídos são apresentados por escrito antes do pagamento.", "Despesas extras e itens não incluídos são discriminados na proposta."],
    message: "Olá! Quero montar um roteiro pela Rota das Emoções."
  },
  "passeio-lado-leste": {
    eyebrow: "Experiências em Jericoacoara",
    title: "Passeio Lado Leste",
    lead: "Conheça paisagens do litoral leste com apoio local e informações claras antes da saída.",
    hero: "/leste-lagoa-aerea.png",
    summary: [["Valor inicial", "R$ 100 por pessoa"], ["Modalidade", "Compartilhada; privativo sob consulta"], ["Duração aproximada", "Cerca de 6 horas"]],
    description: "Paisagens do litoral leste, lagoas paradisíacas e paradas criadas para aproveitar Jericoacoara com conforto, segurança e tempo para contemplar cada cenário.",
    itineraryEyebrow: "Roteiro lado leste",
    itineraryTitle: "Uma jornada entre <em>praias, lagoas e dunas</em>",
    itineraryIntro: "Uma sequência criada para descobrir os cenários mais marcantes do litoral leste de Jericoacoara.",
    itinerary: [["Árvore da Preguiça", "Uma parada estratégica para fotos em um dos cartões-postais mais conhecidos da região."], ["Praia do Preá", "Passagem panorâmica pela vila de pescadores, famosa pelos ventos constantes e pela cultura do kitesurf."], ["Lagun Beach", "Tempo para banho, descanso e para aproveitar com tranquilidade a estrutura local."], ["Buraco Azul", "Uma parada para mergulhar em águas cristalinas e registrar as cores marcantes do lugar."], ["Lagoa do Paraíso", "Visita a uma das lagoas mais famosas de Jericoacoara, com águas calmas e redes dentro d’água."], ["Dunas do Amâncio", "Encerramento com parada para fotos e contemplação das dunas que desenham a paisagem de Jeri."]],
    route: ["Envie a data, quantidade de participantes e local de hospedagem ou embarque.", "A equipe apresenta roteiro, duração aproximada, modalidade e transporte disponíveis.", "Confira valor, inclusões, despesas extras e condições antes de confirmar sua escolha.", "Após a confirmação manual da reserva, receba ponto e horário de encontro pelo WhatsApp."],
    included: ["Transporte conforme modalidade confirmada", "Organização do passeio contratado", "Roteiro, duração e embarque informados antes da confirmação", "Atendimento local pelo WhatsApp"],
    notIncluded: ["Entradas, consumos ou taxas não descritas na proposta", "Alimentação quando não indicada como incluída", "Atividades opcionais contratadas durante o passeio"],
    gallery: [["/leste-arvore-preguica.png", "Árvore da Preguiça no passeio lado leste"], ["/leste-redes.png", "Redes sobre as águas no litoral leste"], ["/leste-dunas-amancio.png", "Dunas do Amâncio no passeio lado leste"]],
    important: ["O valor de R$ 100 é uma referência inicial por pessoa na modalidade compartilhada; opção privativa é cotada conforme grupo e data.", "Roteiro, paradas, duração aproximada, transporte, horário e local de embarque são confirmados na proposta.", "Entradas, alimentação, atividades opcionais e eventuais taxas são informadas separadamente quando não incluídas.", "Condições naturais podem exigir ajustes no roteiro."],
    message: "Olá! Quero cotar o Passeio Lado Leste em Jericoacoara."
  }
};
